#+title: Module 3 Homework

Using the [[https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page][2022 Green Taxi Trip Record Parquet files]]
1. Create an external table
2. Create a table in BigQuery (without partitioning or clustering)

* Count records

What is count of records for the 2022 Green Taxi Data?

- [ ] 65,623,481
- [ ] 840,402
- [ ] 1,936,423
- [ ] 253,647

* Count distinct =PULocationIDs=

Write a query to count the distinct number of PULocationIDs for the entire dataset on both the tables.
What is the estimated amount of data that will be read when this query is executed on the External Table and the Table?

- [ ] 0 MB for the External Table and 6.41MB for the Materialized Table
- [ ] 18.82 MB for the External Table and 47.60 MB for the Materialized Table
- [ ] 0 MB for the External Table and 0MB for the Materialized Table
- [ ] 2.14 MB for the External Table and 0MB for the Materialized Table

* Count records with =fare_amount= of 0

How many records have a =fare_amount= of 0?

- [ ] 12,488
- [ ] 128,219
- [ ] 112
- [ ] 1,622

* Best strategy for query

What is the best strategy to make an optimized table in Big Query if your query will always order the results by =PUlocationID= and filter based on =lpep_pickup_datetime=? (Create a new table with this strategy)

- [ ] Cluster on =lpep_pickup_datetime= Partition by =PUlocationID=
- [ ] Partition by =lpep_pickup_datetime= Cluster on =PUlocationID=
- [ ] Partition by =lpep_pickup_datetime= and Partition by =PUlocationID=
- [ ] Cluster on by =lpep_pickup_datetime= and Cluster on =PUlocationID=

* Distinct =PuLocationID= in date range

Write a query to retrieve the distinct =PULocationID= between =lpep_pickup_datetime= 06/01/2022 and 06/30/2022 (inclusive)

Use the materialized table you created earlier in your from clause and note the estimated bytes.
Now change the table in the from clause to the partitioned table you created for question 4 and note the estimated bytes processed.
What are these values?

Choose the answer which most closely matches.

- [ ] 22.82 MB for non-partitioned table and 647.87 MB for the partitioned table
- [ ] 12.82 MB for non-partitioned table and 1.12 MB for the partitioned table
- [ ] 5.63 MB for non-partitioned table and 0 MB for the partitioned table
- [ ] 10.31 MB for non-partitioned table and 10.31 MB for the partitioned table

* Location of external table

Where is the data stored in the External Table you created?

- [ ] Big Query
- [ ] GCP Bucket
- [ ] Big Table
- [ ] Container Registry

* Clustering in Big Query

It is best practice in Big Query to always cluster your data:

- [ ] True
- [ ] False

* Bonus

No Points: Write a =SELECT count(*)= query FROM the materialized table
you created. How many bytes does it estimate will be read? Why?

* Submitting the solutions

- Form for submitting: https://courses.datatalks.club/de-zoomcamp-2024/homework/hw3
